controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/GripperActionController

gripper_controller:
  ros__parameters:
    joint: gripper_joint
    action_monitor_rate: 20.0
    allow_stalling: true
    stall_velocity_threshold: 0.01
    stall_timeout: 0.5
    goal_tolerance: 0.05
    max_effort: 0.01