# ROS State
int32 K_ROS_NONE=0
# Cancel
int32 K_ROS_CANCEL=-2
# Failure
int32 K_ROS_FAILURE=-1
# Complete
int32 K_ROS_SUCCESS=1
# Executing
int32 K_ROS_EXECUTING=2
# Pause
int32 K_ROS_PAUSE=3
# Pause Failure
int32 K_ROS_PAUSE_FAILED=4
# Execution Failure
int32 K_ROS_EXECUTE_FAILED=5
# Exception Message
int32 K_ROS_ERR_MSG=10
# WiFi Request Status Code
int32 K_ROS_WI_FI_CODE=100
# WiFi Information JSON
int32 K_ROS_WI_FI_JSON=101

int32 value
