# Robot Hardware Device Bit Information
int32 K_HARDWARE_BIT_UNDEFINED=0
# Button 1 (Pause/Continue/Next)
int32 K_BTN1=1
# Button 2 (Reset)
int32 K_BTN2=2
# Button 3
int32 K_BTN3=4
# Button 4
int32 K_BTN4=8
# Button 5
int32 K_BTN5=16
# Button 6
int32 K_BTN6=32
# Button 7
int32 K_BTN7=64
# Button 8
int32 K_BTN8=128
# Servo Release Button
int32 K_SERVO_BTN=256
# Lift Button
int32 K_LIFT_BTN=512
# Emergency stop triggered
int32 K_EMG_BTN=1024

int32 value
