# Robot Info - composite of all robot information
woosh_robot_msgs/General genral
woosh_robot_msgs/Setting setting
woosh_robot_msgs/State state
woosh_robot_msgs/Mode mode
woosh_robot_msgs/PoseSpeed pose_speed
woosh_robot_msgs/Battery battery
woosh_robot_msgs/Network network
woosh_robot_msgs/Scene scene
woosh_robot_msgs/TaskProc task_proc
woosh_robot_msgs/DeviceState device_state
woosh_robot_msgs/OperationState operation_state
woosh_robot_msgs/Model model
